server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
    
  application:
      name: appgate-challenge
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_URL:192.168.0.248:3306}/${MYSQL_DATABASE:Appgate}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
        username: ${MYSQL_USER:finallydate}
        password: ${MYSQL_PASSWORD:GV4r+HVNBHUxsBTc}

  jpa:
      show-sql: false
      hibernate:
          ddl-auto: update
          naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQL5InnoDBDialect
file:
  upload-dir: /tmp/uploads/appgate/
