server:
  port: 8095
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
    
  application:
      name: appgate-challenge
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.0.248:3306/Appgate?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
        username: finallydate
        password: GV4r+HVNBHUxsBTc

  jpa:
      show-sql: true
      hibernate:
          ddl-auto: update
          naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQL5InnoDBDialect
file:
  upload-dir: /tmp/uploads/
